export default {
    ChannelId: 'aurora',
    NoInit: 'noinit',
    PackageId: 'noinit',//package id + apk id 3/12 改为 只有apkid
    UserLevel: 1,
    All: 'All',

    EventId: {
        CHANGE_APK_ID: 'change_apk_id',
        CHANNEL_APK_VISIBLE: 'channel_apk_visible',
        UPDATE_APK_ID: 'UPDATE_APK_ID', // 修改渠道包配置后,通知hearder重新请求
    },

    RoutePath: {
        RealTime_Data:          '/realtime_data',
        Realtime_Session:       '/realtime_session',
        Realtime_Room:          '/realtime_room',
        Event_Data:             '/event_data',
        Package_Data:           '/package_data',
        Channel_Data:           '/channel_data',
        User_Keep:              '/user_keep',
        User_Lose_Gold:         '/user_lose_gold',
        Recharge_Data:          '/recharge_data',
        Active_Data:            '/active_data',
        User_Data:              '/user_data',
        Session_Data:           '/session_data',
        Play_Game_Data:         '/play_game_data',
        Gold_Surplus:           '/gold_surplus',
        Important_Data:         '/important_data',
        Gold_Query:             '/gold_query',
        Recharge_Query:         '/recharge_query',
        Create_Order:           '/create_order',
        Recharge_Statistics:    '/recharge_statistics',
        Withdraw_Manage:        '/withdraw_manage',
        KYC_Manage:             '/kyc_manage',
        OTP_Query:              '/otp_query',
        Invite_Query:           '/invite_query',
        User_Gears:             '/user_gears',
        GM_User_Read:           '/gm_user_read',
        Session_Rummy:          '/session_rummy',
        Session_TeenPatti:      '/session_teenpatti',
        Session_TwoPersons_Rummy: '/session_rummy_2p',
        Session_TeenPatti_Speed: '/session_teenpatti_speed',
        Session_Practice:       '/session_practice',
        Session_AK47:           '/session_ak47',
        Session_Lowest_Joker:   '/session_lowest_joker',
        Session_Highest_Joker:  '/session_highest_joker',
        Session_Dragon_Tiger:   '/session_dragon_tiger',
        GoldPool_Rummy:         '/goldpool_rummy',
        GoldPool_TeenPatti:     '/goldpool_teenpatti',
        GoldPool_gear:          '/goldpool_gear',
        AI_Rummy:               '/ai_rummy',
        AI_Rummy_robot:         '/ai_rummy_robot',
        AI_Rummy2User:          '/ai_rummy2user',
        AI_Rummy2User_Robot:    '/ai_rummy2user_robot',
        AI_Teenpatti:           '/ai_teenpatti',
        AI_TPRecharge:          '/ai_tp_recharge',
        AI_AK47:                '/ai_ak47',
        AI_Lowest_Joker:        '/ai_lowest_joker',
        AI_Highest_Joker:       '/ai_highest_joker',
        AI_Dragon_Tiger:        '/ai_dragon_tiger',
        AI_Switch:              '/ai_switch',
        AI_Filling:             '/ai_filling',
        AI_Filling_TP:          '/ai_filling_tp',
        AI_Session_Limit:       '/ai_session_limit',
        AI_Trigger_Config:      '/ai_trigger_config',
        AI_Trigger_Config_R:    '/ai_trigger_config_r',
        AI_Event_Config:        '/ai_event_config',
        AI_Operation_Config:    '/ai_operation_config',
        AI_Recharge_Card_Config:'/ai_recharge_card_config',
        Robot_Rummy:            '/robot_rummy',
        Robot_Teenpatti:        '/robot_teenpatti',
        Activity_Login:         '/activity_login',
        Activity_Turntable:     '/activity_turntable',
        Activity_Invite:        '/activity_invite',
        Activity_NewUserGive:   '/activity_newusergive',
        Activity_Limit:         '/activity_limit',
        Activity_First:         '/activity_first',
        Bulletin_Board:         '/bulletin_board',
        Activity_Show:          '/activity_show',
        Weeks_Card:             '/weeks_card',
        Balance_Pop_Up:         '/balance_pop_up',
        New_User_Recharge:      '/new_user_recharge',
        Shop_BMart_Config:      '/shop_bmart_config',
        Shop_Funzone_Config:    '/shop_funzone_config',
        Shop_SerPay_Config:     '/shop_serpay_config',
        Shop_Payway_Config:     '/shop_payway_config',
        Shop_Other_Config:      '/shop_other_config',
        Withdraw_Game:          '/withdraw_game',
        Withdraw_Payout:        '/withdraw_payout',
        System_Config:          '/system_config',
        Game_Player:            '/game_player',
        Card_Type:              '/Card_Type',
        Recharge_And_Rank:      '/recharge_and_rank',
        Gold_Pool_Config:       '/gold_pool_config',
        Gold_Pool_Add:          '/gold_pool_add',
        Mail_System:            '/mail_system',
        Mail_User:              '/mail_user',
        Mail_Cancel:            '/mail_cancel',
        Mail_Recharge_Success:  '/mail_recharge_success',
        Mail_Recharge_Fail:     '/mail_recharge_fail',
        GM_User:                '/gm_user',
        GM_Marquee:             '/gm_marquee',
        GM_Marquee_Game:        '/gm_marquee_game',
        GM_Update:              '/gm_update',
        GM_Recharge:            '/gm_recharge',
        GM_PayOut:              '/gm_payout',
        Channel_Package:        '/channel_package',
        Log_Operation:          '/log_operation',

        Online_Recharge_Charts: '/online_recharge_charts',
        User_Gold_Charts:       '/user_gold_charts',
        PC_Info_Charts:         '/pc_info_charts',
        Session_Charts:         '/session_charts',

        Active_User_Sift:         '/active_user_sift',

        OTP_Config:             '/otp_config',
        Activity_Limit_Data:    '/activity_limit_data',
        Go_Broke_Data:          '/go_broke_data',
        New_User_Recharge_Data: '/new_user_recharge_data',
        Dot_Data:               '/dot_data'
    }

}
